# ssh-keygen -t rsa -b 4096 -C danielfdsilva/harness-pixels -f deploy_key
version: 2
jobs:
  build:
    docker:
      - image: node:7

    working_directory: ~/repo

    environment:
      - DEPLOY_BRANCH: master
      - GH_REF: git@github.com:danielfdsilva/harness-pixels.git
      - GH_NAME: "Daniel da Silva"
      - GH_EMAIL: "mailpatudo@gmail.com"

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test

      - add_ssh_keys:
          fingerprints:
            - "29:a3:af:95:90:14:5f:76:6d:01:66:34:3b:1e:1c:f0"

      - run: 
          name: Building site
          command: |
            if [ "${CIRCLE_BRANCH}" == "${DEPLOY_BRANCH}" ]; then
              node metalsmith.js
            else
              echo "Skip building site"
            fi

      - run:
          name: Deploy to GH Pages
          command: |
            if [ "${CIRCLE_BRANCH}" == "${DEPLOY_BRANCH}" ]; then
              cd build
              git init
              git config user.name "$GH_NAME"
              git config user.email "$GH_EMAIL"
              git add .
              git commit -m "CI deploy [skip ci]"
              git remote add origin $GH_REF
              git push origin --force --quiet HEAD:gh-pages
              rm -rf .git
            else
              echo "Skip deploying to Github"
            fi